### ISSUE TITLE
Last letter in the chain gets a transition probability with itself of 1

### ISSUE THREAD

**Issue by eldraco** [riccardoscalco/Pykov#14]
import pykov
import math
init_vector, matrix = pykov.maximum_likelihood_probabilities('99a')
math.exp(matrix.walk_probability('99'))
Out[26]: 0.5
math.exp(matrix.walk_probability('ee'))
Out[27]: 0.0
math.exp(matrix.walk_probability('aa'))
Out[28]: 1.0
matrix
Out[30]: {('9', '9'): 0.5, ('9', 'a'): 0.5, ('a', 'a'): 1.0}

Do you know why you get this extra transition a->a=1 ?

Git commit:
9dc9181fbd766bf1d6b4becb6791e875c42a5175

**Comment by riccardoscalco** [comment]
Hi eldraco,

that extra transition comes from the " _remove_dead_branch" function. It is an heuristic method useful to get a right stochastic matrix from a chain of states (each row summing to 1). In your example, the ('a','a') link is added in order assign outgoing links to 'a', if your initial chain was  '99a9' the extra link would not be added. 

The function is called at the third line on "maximum_likelihood_probabilities", and you can easily substitute it with your own heuristic.

**Comment by eldraco** [comment]
Thanks a lot! I will see to do it. It was difficult to understand why it is telling me that the prob was 1 when actually it should not be there in the matrix.
Thanks 
Sebas
