### ISSUE TITLE
Set module removed in python 3

### ISSUE THREAD

**Issue by CrazyPython** [riccardoscalco/Pykov#15]
Now there is an `ImportError` when importing pykov in Python 3.

**Comment by CrazyPython** [comment]
#16

**Comment by CrazyPython** [comment]
#16

**Comment by monkpit** [comment]
This needs to be fixed somehow - ran into this problem today - @riccardoscalco is there anything I can do to help? In my opinion the code should be rewritten to use `set` by default instead of `sets.Set`.

**Comment by riccardoscalco** [comment]
Merged #16

Sorry for the lazy maintenance.

**Comment by CrazyPython** [comment]
Merged - Now compatible. @riccardoscalco make sure to update it on PyPI
