### ISSUE TITLE
Make a documentation on ReadTheDoc

### ISSUE THREAD

**Issue by Naereen** [riccardoscalco/Pykov#27]
Hi,

First, thanks and :clap: for this small and cool project.
It's neat and well written, I love it!

Second, may I suggest that you write a Sphinx documentation and host it on [ReadTheDocs](https://www.ReadTheDocs.org) please?
Based on the Markdown documentation that is already available in the README.md file, it could be very easy.

GitHub can be connected to ReadTheDocs to build the site automatically, for instance http://pykov.readthedocs.org/

Thanks in advance; I can't do it for you, but if you need any help, I can assist (I did a few docs on ReadTheDocs already, see [this example](http://mec-cs101-matrices.rtfd.io/) or [this one](http://ansicolortags.rtfd.io/)).

**Comment by Naereen** [comment]
Using the [autodoc Sphinx extension](http://www.sphinx-doc.org/en/stable/ext/autodoc.html), and [apidoc](http://www.sphinx-doc.org/en/stable/man/sphinx-apidoc.html) to generate a reStructuredText file, I obtained a documentation directly from the `pykov.py` file, with no sweat. :sunglasses:

It's not 100% complete (based on the docstrings, which are not as complete as what you did in the README.md), but it looks nice:
![example_pykov_documentation](https://cloud.githubusercontent.com/assets/11994719/25538938/0338e21e-2c45-11e7-80bf-da39dd59b9b9.png)
(default ReadTheDocs theme)

**Comment by riccardoscalco** [comment]
Hi, thanks for the suggestion and help.

I used a single readme for the documentation because Pykov APIs are quite few and because I wanted to reduce maintenance effort.

Read the Docs provides a webhook for github, so this weekend I subscribed and did the few steps necessary to build documentation from the README.md file.
According to this docs (https://docs.readthedocs.io/en/latest/builds.html#mkdocs) the existence of a README.md file is sufficient for the creation of a page, but at the moment the page still does not exist, which is weird. Do you have any suggestion?

**Comment by Naereen** [comment]
Hi,
You are welcome, I will try to help.

I never used Read the Docs with MkDocs.
- Maybe you can try to write yourself a `mkdocs.yml` with minimal configuration,
- Maybe you can ask to build the documentation manually and not wait for a webhook (if you didn't committed anything on GitHub, the webhook has no reason to have been activated). In the build page there is the log file of the building process, you can see if anything fails,
- You can install MkDocs on your machine, and check that it successively builds a HTML doc from your one file README.md : if it fails, no need to hope for the automated platform to success!

**Comment by riccardoscalco** [comment]
Thanks for the tips, as first attempt I do a `mkdocs.yml` and see what happens. I let you know in case of success.

**Comment by Naereen** [comment]
Hi @riccardoscalco,
Any update?

**Comment by riccardoscalco** [comment]
Not yet, sorry. I am stuck on the the creation of docs from the README.md file.
Anyway, I think that for such small project a single readme in github is enough.

**Comment by Naereen** [comment]
Hi,
No problem. As you prefer.
